name: Get Thumbprint
description: Extract the thumbprint from the x509 certificate
inputs:
  PfxPassword:
    required: true
    description: "The PFX password"
outputs:
  thumbprint:
    value: ${{ steps.thumbprint-output.outputs.thumbprint }}
runs:
  using: "composite"
  steps:
    - run: |
        cd repo
        $x509 = Get-PfxCertificate -FilePath ./key.pfx -Password (ConvertTo-SecureString -String "${{ inputs.PfxPassword }}" -AsPlainText -Force)
        $Thumbprint = $x509.ThumbPrint
        # Pass thumbprint to later job.
        echo thumbprint=$Thumbprint >> $env:GITHUB_OUTPUT
      id: thumbprint-output
      # -Password flag requires PS 6+
      shell: pwsh
