# Purpose: Run the linter against the PowerShell code

name: Lint Check for PowerShell

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  powershell-lint-check:
    name: PowerShell Check
    runs-on: windows-latest
    # This condition prevents duplicate runs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        run: |
          # Source the function
          . ./utils/workflow/Invoke-PSSA.ps1
          Invoke-PSSA -DebuggingMode $false -RepoPath '.'
